language: php

sudo: false

php:
  - hhvm
  - 5.6
  - 5.5
  - 5.4
  - 5.3

branches:
  only:
    - master
    - development
       
script:
  - cd src
  - php index.php
  - cd ..
  - phpunit --configuration ./phpunit.xml --coverage-text
